server:
  port: 8080
spring:
  application:
    name: ety-natively
  profiles:
    active: dev
    default: prod
logging:
  level:
    sql: info
    com.ety.natively: info
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ety.natively
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
natively:
  jwt:
    private-key-path: security/private.key
    public-key-path: security/public.key
  swagger:
    author: sb
    description: nmsl
    base-package: com.ety.natively
    title: NMSL
    email: null
    license: Apache
    version: 1
  auth:
    no-auth-path:
      - /user/login
      - /user/register
      - /user/username
      - /user/refresh
      - /general/location/**
      - /general/language/**
      - /user/oauth2/**
      - /test/**
      - /ws/**
      - /chat/connect/**
      - /language/lang/**
      - /language/explanation/stream